# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChartView
from PyQt5.QtWidgets import *

class Ui_mainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("熔渣测速")
        mainWindow.resize(1672, 1024)
        mainWindow.setMinimumSize(1400, 900)

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        mainWindow.setCentralWidget(self.centralwidget)

        # ===== 总体布局 =====
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(10, 10, 10, 10)
        self.mainLayout.setSpacing(10)

        # ===== 顶部返回 =====
        self.topBarLayout = QtWidgets.QHBoxLayout()
        self.return_ui = QtWidgets.QPushButton("返回")
        self.return_ui.setMinimumSize(60, 36)
        self.return_ui.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.topBarLayout.addWidget(self.return_ui, alignment=QtCore.Qt.AlignLeft)
        self.topBarLayout.addStretch()
        self.mainLayout.addLayout(self.topBarLayout)

        # ===== 主内容左右布局 =====
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.mainLayout.addLayout(self.contentLayout)

        # =========================================================
        # 左侧：流速区域
        # =========================================================
        self.flowratewidget = QtWidgets.QWidget()
        self.flowratewidget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.contentLayout.addWidget(self.flowratewidget, 2)

        self.flowMainLayout = QtWidgets.QVBoxLayout(self.flowratewidget)
        self.flowMainLayout.setContentsMargins(0, 0, 0, 0)
        self.flowMainLayout.setSpacing(10)

        # ---------- 第1行：参数显示框 + 参数设置 ----------
        self.flowTopInfoLayout = QtWidgets.QHBoxLayout()
        self.flowTopInfoLayout.setSpacing(10)

        self.flowInfo = QtWidgets.QTextBrowser()
        self.flowInfo.setMinimumHeight(110)
        self.flowInfo.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.flowInfo.setFont(font)

        self.crossInfo = QtWidgets.QTextBrowser()
        self.crossInfo.setMinimumHeight(110)
        self.crossInfo.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.crossInfo.setFont(font)

        self.paramBtnLayout = QtWidgets.QVBoxLayout()
        self.paramBtnLayout.setSpacing(10)

        self.flowratecamera_param_control = QtWidgets.QPushButton("流速硬件参数设置")
        self.flowratecamera_param_control.setMinimumHeight(36)
        self.flowratecamera_param_control.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self.crosssectcamera_param_control = QtWidgets.QPushButton("截面积硬件参数设置")
        self.crosssectcamera_param_control.setMinimumHeight(36)
        self.crosssectcamera_param_control.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self.paramBtnLayout.addWidget(self.flowratecamera_param_control)
        self.paramBtnLayout.addWidget(self.crosssectcamera_param_control)

        self.flowTopInfoLayout.addWidget(self.flowInfo, 3)
        self.flowTopInfoLayout.addWidget(self.crossInfo, 3)
        self.flowTopInfoLayout.addLayout(self.paramBtnLayout, 2)

        self.flowMainLayout.addLayout(self.flowTopInfoLayout)

        # ---------- 第2行：打开相机 / 关闭相机 ----------
        self.flowCamRow = QtWidgets.QHBoxLayout()
        self.flowCamRow.setSpacing(10)

        self.flowrate_OpenCam = QtWidgets.QPushButton("打开相机")
        self.flowrate_CloseCam = QtWidgets.QPushButton("关闭相机")

        for btn in [self.flowrate_OpenCam, self.flowrate_CloseCam]:
            btn.setMinimumHeight(36)
            btn.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
            self.flowCamRow.addWidget(btn)

        self.flowMainLayout.addLayout(self.flowCamRow)

        # ---------- 第3行：采集 + 测速按钮 ----------
        self.flowActionRow = QtWidgets.QHBoxLayout()
        self.flowActionRow.setSpacing(10)

        self.flowrate_single = QtWidgets.QPushButton("单帧采集")
        self.flowrate_continuous = QtWidgets.QPushButton("连续采集")
        self.flowrate_choose_roi = QtWidgets.QPushButton("框选测速范围")
        self.flowrate_Trad_start = QtWidgets.QPushButton("开始传统测速")
        self.flowrate_xFeat_start = QtWidgets.QPushButton("开始深度学习测速")

        for btn in [
            self.flowrate_single,
            self.flowrate_continuous,
            self.flowrate_choose_roi,
            self.flowrate_Trad_start,
            self.flowrate_xFeat_start
        ]:
            btn.setMinimumHeight(36)
            btn.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
            self.flowActionRow.addWidget(btn)

        self.flowMainLayout.addLayout(self.flowActionRow)

        # ---------- 第4行：图像显示 ----------
        self.flowImageLayout = QtWidgets.QHBoxLayout()
        self.flowImageLayout.setSpacing(8)

        self.flowrate_Cam = QtWidgets.QLabel()
        self.flowrate_Cam.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.flowrate_Cam.setAlignment(QtCore.Qt.AlignCenter)
        self.flowrate_Cam.setMinimumSize(500, 420)
        self.flowrate_Cam.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.flowrate_Cam_Seg = QtWidgets.QLabel()
        self.flowrate_Cam_Seg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.flowrate_Cam_Seg.setAlignment(QtCore.Qt.AlignCenter)
        self.flowrate_Cam_Seg.setMinimumSize(320, 420)
        self.flowrate_Cam_Seg.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.flowImageLayout.addWidget(self.flowrate_Cam, 3)
        self.flowImageLayout.addWidget(self.flowrate_Cam_Seg, 2)

        self.flowMainLayout.addLayout(self.flowImageLayout, 5)

        # ---------- 第5行：底部曲线（高度加大） ----------
        self.flowrate_plot_view = QChartView()
        self.flowrate_plot_view.setObjectName("flowrate_plot_view")
        self.flowrate_plot_view.setMinimumHeight(520)
        self.flowrate_plot_view.setMaximumWidth(720)
        self.flowrate_plot_view.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.flowMainLayout.addWidget(self.flowrate_plot_view, 3)

        # =========================================================
        # 右侧：截面积区域
        # =========================================================
        self.crosssectwidget = QtWidgets.QWidget()
        self.crosssectwidget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.contentLayout.addWidget(self.crosssectwidget, 1)

        self.crossMainLayout = QtWidgets.QVBoxLayout(self.crosssectwidget)
        self.crossMainLayout.setContentsMargins(0, 0, 0, 0)
        self.crossMainLayout.setSpacing(10)

        # ---------- 第1行：打开相机 / 关闭相机 ----------
        self.crossCamRow = QtWidgets.QHBoxLayout()
        self.crossCamRow.setSpacing(10)

        self.crosssect_OpenCam = QtWidgets.QPushButton("打开相机")
        self.crosssect_CloseCam = QtWidgets.QPushButton("关闭相机")

        for btn in [self.crosssect_OpenCam, self.crosssect_CloseCam]:
            btn.setMinimumHeight(36)
            btn.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
            self.crossCamRow.addWidget(btn)

        self.crossMainLayout.addLayout(self.crossCamRow)

        # ---------- 第2行：采集 + 计算 ----------
        self.crossActionRow = QtWidgets.QHBoxLayout()
        self.crossActionRow.setSpacing(10)

        self.crosssect_continuous = QtWidgets.QPushButton("开始采集")
        self.crosssect_start = QtWidgets.QPushButton("开始截面积计算")
        self.bottom_face_start = QtWidgets.QPushButton("开始下底面面积计算")

        for btn in [self.crosssect_continuous, self.crosssect_start, self.bottom_face_start]:
            btn.setMinimumHeight(36)
            btn.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
            self.crossActionRow.addWidget(btn)

        self.crossMainLayout.addLayout(self.crossActionRow)

        # ---------- 第3行：相机画面 ----------
        self.crosssect_Cam = QtWidgets.QLabel()
        self.crosssect_Cam.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.crosssect_Cam.setAlignment(QtCore.Qt.AlignCenter)
        self.crosssect_Cam.setMinimumSize(360, 460)
        self.crosssect_Cam.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.crossMainLayout.addWidget(self.crosssect_Cam, 5)

        # ---------- 第4行：底部曲线（高度加大） ----------
        self.crosssect_plot_view = QChartView()
        self.crosssect_plot_view.setObjectName("crosssect_plot_view")
        self.crosssect_plot_view.setMinimumHeight(520)
        self.crosssect_plot_view.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.crossMainLayout.addWidget(self.crosssect_plot_view, 3)

        # menubar / statusbar
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        mainWindow.setStatusBar(self.statusbar)
        # ===== 小按钮样式标记 =====
        self.flowrate_OpenCam.setObjectName("smallBtn")
        self.flowrate_CloseCam.setObjectName("smallBtn")
        self.flowrate_single.setObjectName("smallBtn")
        self.flowrate_continuous.setObjectName("smallBtn")
        self.flowrate_choose_roi.setObjectName("smallBtn")
        self.flowrate_Trad_start.setObjectName("smallBtn")
        self.flowrate_xFeat_start.setObjectName("smallBtn")

        self.crosssect_OpenCam.setObjectName("smallBtn")
        self.crosssect_CloseCam.setObjectName("smallBtn")
        self.crosssect_continuous.setObjectName("smallBtn")
        self.crosssect_start.setObjectName("smallBtn")
        self.bottom_face_start.setObjectName("smallBtn")

        self.return_ui.setObjectName("smallBtn")
        self.flowratecamera_param_control.setObjectName("smallBtn")
        self.crosssectcamera_param_control.setObjectName("smallBtn")
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "mainWindow"))