# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChartView
from PyQt5.QtWidgets import *


class LoginWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Login")
        self.setGeometry(500, 300, 200, 100)

        # 创建布局
        self.layout = QVBoxLayout()

        # 创建密码输入框
        self.password_label = QLabel("请输入密码")
        self.layout.addWidget(self.password_label)
        self.password_input = QLineEdit()
        self.password_input.setEchoMode(QLineEdit.Password)  # 密码框
        self.layout.addWidget(self.password_input)

        # 创建登录按钮
        self.login_button = QPushButton("登录")
        self.layout.addWidget(self.login_button)

        # 设置布局
        self.setLayout(self.layout)

        # 登录按钮点击事件
        self.login_button.clicked.connect(self.check_password)

    def check_password(self):
        # 获取输入的密码
        password = self.password_input.text()

        # 简单密码验证
        if password == "c1403":
            self.accept()  # 关闭登录界面，返回接受状态
        else:
            QMessageBox.warning(self, "错误", "密码错误，请重试！")
class Simplified_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.simplewidget = QtWidgets.QWidget(self.centralwidget)
        self.simplewidget.setGeometry(QtCore.QRect(50, 50, 1100, 760))
        self.simplewidget.setObjectName("simplewidget")
        self.simple_flowrate_plot_view = QChartView(self.simplewidget)
        self.simple_flowrate_plot_view.setGeometry(QtCore.QRect(580, 70, 490, 320))
        self.simple_flowrate_plot_view.setObjectName("plot_view")
        self.simple_crosssect_plot_view = QChartView(self.simplewidget)
        self.simple_crosssect_plot_view.setGeometry(QtCore.QRect(580, 400, 490, 320))
        self.simple_crosssect_plot_view.setObjectName("plot_view")
        self.simple_traffic_plot_view = QChartView(self.simplewidget)
        self.simple_traffic_plot_view.setGeometry(QtCore.QRect(30, 210, 490, 320))
        self.simple_traffic_plot_view.setObjectName("plot_view")
        # 设置openprojectui按钮
        self.openprojectui = QtWidgets.QPushButton(self.simplewidget)
        self.openprojectui.setGeometry(QtCore.QRect(20, 570, 50, 50))
        self.openprojectui.setObjectName("openprojectui")
        # self.openprojectui.setStyleSheet("""
        #     QPushButton#openprojectui {
        #         border: none;
        #         border-image: url('utils\splash\set.png') 0 0 0 0 stretch stretch;
        #     }
        # """)

        self.stop = QtWidgets.QPushButton(self.simplewidget)
        self.stop.setGeometry(QtCore.QRect(310, 20, 160, 30))
        self.stop.setObjectName("stop")
        self.start = QtWidgets.QPushButton(self.simplewidget)
        self.start.setGeometry(QtCore.QRect(60, 20, 160, 30))
        self.start.setObjectName("start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop.setText(_translate("MainWindow", "结束流量检测"))
        self.start.setText(_translate("MainWindow", "开始流量检测"))
        self.openprojectui.setText(_translate("MainWindow", "设置"))
