# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChartView
from PyQt5.QtWidgets import *


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("熔渣测速")
        MainWindow.resize(1672, 1024)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CloseCam = QtWidgets.QPushButton(self.centralwidget)
        self.CloseCam.setGeometry(QtCore.QRect(280, 40, 221, 51))
        self.CloseCam.setObjectName("CloseCam")
        self.Cam = QtWidgets.QLabel(self.centralwidget)
        self.Cam.setGeometry(QtCore.QRect(60, 130, 911, 751))
        self.Cam.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Cam.setText("")
        self.Cam.setObjectName("Cam")
        self.Cam_Seg = QtWidgets.QLabel(self.centralwidget)
        self.Cam_Seg.setGeometry(QtCore.QRect(1080, 250, 531, 371))
        self.Cam_Seg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Cam_Seg.setText("")
        self.Cam_Seg.setObjectName("Cam_Seg")
        self.single = QtWidgets.QPushButton(self.centralwidget)
        self.single.setGeometry(QtCore.QRect(520, 40, 221, 51))
        self.single.setObjectName("single")
        self.continuous = QtWidgets.QPushButton(self.centralwidget)
        self.continuous.setGeometry(QtCore.QRect(760, 40, 221, 51))
        self.continuous.setObjectName("continuous")
        self.Info = QtWidgets.QTextBrowser(self.centralwidget)
        self.Info.setEnabled(True)
        self.Info.setGeometry(QtCore.QRect(1080, 30, 531, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Info.setFont(font)
        self.Info.setObjectName("Info")
        self.Trad_start = QtWidgets.QPushButton(self.centralwidget)
        self.Trad_start.setGeometry(QtCore.QRect(290, 890, 221, 51))
        self.Trad_start.setObjectName("Trad_start")
        self.xFeat_start = QtWidgets.QPushButton(self.centralwidget)
        self.xFeat_start.setGeometry(QtCore.QRect(520, 890, 221, 51))
        self.xFeat_start.setObjectName("xFeat_start")

        self.plot_view = QChartView(self.centralwidget)
        self.plot_view.setGeometry(QtCore.QRect(1080, 650, 531, 371))
        self.plot_view.setObjectName("plot_view")

        self.OpenCam = QtWidgets.QPushButton(self.centralwidget)
        self.OpenCam.setGeometry(QtCore.QRect(50, 40, 221, 51))
        self.OpenCam.setObjectName("OpenCam")
        self.choose_roi = QtWidgets.QPushButton(self.centralwidget)
        self.choose_roi.setGeometry(QtCore.QRect(60, 890, 221, 51))
        self.choose_roi.setObjectName("choose_roi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1672, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CloseCam.setText(_translate("MainWindow", "关闭相机"))
        self.single.setText(_translate("MainWindow", "单帧采集"))
        self.continuous.setText(_translate("MainWindow", "连续采集"))
        self.Trad_start.setText(_translate("MainWindow", "开始传统测速"))
        self.OpenCam.setText(_translate("MainWindow", "打开相机"))
        self.choose_roi.setText(_translate("MainWindow", "框选测速范围"))
        self.xFeat_start.setText(_translate("MainWindow", "开始深度学习测速"))




